### ISSUE TITLE
Readme的单词拼写问题。

### ISSUE THREAD

**Issue by irrienberith** [AnotherNote/anote#1]
![default](https://cloud.githubusercontent.com/assets/6916194/18737686/37cf1cf2-80c7-11e6-863b-6dd9603142fd.PNG)

单词拼写问题，`past`应该是`paste`吧？
另外最好有个中文的readme，谢谢！

**Comment by wpzero** [comment]
thx, 学生时代没有好好学习英文，谢谢，有兴趣一起玩？
